### PR TITLE
fix: unify paginator interface

### LINKED ISSUE #1449: InfiniteScrollPaginator not working as expected
We are using the infinite scroll feature to try and get all the channels for the user.

The expected is that the `ChannelList` will load channels automatically.

It appears the component is not doing multiple chunk request of 30 channels at the time as when checking the network traffic, there is only one request and for some reason the API is returning only 28 channels out of 100 that my user has.

image

The code I used to replicate the issue is:

```
import React from 'react'
import { ChannelSort, StreamChat } from 'stream-chat'
import {
  Channel,
  ChannelHeader,
  ChannelList,
  Chat,
  InfiniteScrollPaginator,
  MessageInput,
  MessageList,
  Thread,
  useChannelStateContext,
  Window,
} from 'stream-chat-react'
import 'stream-chat-react/dist/css/index.css'

const appId = 'hhraee329mye'
const messagingUserId =
  '00010e42-8a60-45f9-be6e-4dda93c8683d@sk_1d8b120bc51d4ce7af222bd63f385155'

const baseFilters = {
  type: 'CHANNEL',
  members: { $in: [messagingUserId] },
  team: teamId,
}

const channelFilters = {
  ...baseFilters,
  category: 'CHANNEL',
}

const sort = {
  name: 1,
} as ChannelSort

const chatUser = {
  id: messagingUserId,
  name: 'Alex Lopez CP',
  role: 'admin',
}

const options = {
  limit: 30,
  state: true,
  watch: true,
  presence: true,
}
function App() {
  const [client, setClient] = React.useState<StreamChat | null>(null)

  React.useEffect(() => {
    const newClient = StreamChat.getInstance(appId)
    setClient(newClient)
    newClient.connectUser(chatUser, userToken)
  }, [])

  if (!client) {
    return <div>Connecting</div>
  }

  return (
    <Chat client={client} theme='team light'>
      <ChannelList
        filters={channelFilters}
        sort={sort}
        options={options}
        Paginator={InfiniteScrollPaginator}
      />
      <Channel>
        <Window>
          <ChannelHeader />
          <MessageList />
          <MessageInput />
        </Window>
        <Thread />
      </Channel>
    </Chat>
  )
}
```

### PR DESCRIPTION
**Pull request by MartinCupela**
### 🎯 Goal

Allow integrators to use `InfiniteScroll` component with `ChannelList`. The integrators can now pass the `InfiniteScroll` to `ChannelList` prop `Paginator`. For furthe configuration a wrapper around the `InfiniteScroll` is needed.

The feature depends on CSS changes in https://github.com/GetStream/stream-chat-css/pull/206

Fixes #1449

**Out of scope**
Positioning of loading indicator depending on the loading direction (loading older items vs newer items - indicator at the top vs. bottom of the list) 
Issue: #1805

### 🛠 Implementation details

Unify the paginator API through a base type `PaginatorProps`. Both `InfiniteScrollProps` as well as `LoadMorePaginatorProps` now inherit from `PaginatorProps` base type. Props that did not match between these 2 types were deprecated. The deprecated props are still accepted if the newly named props are not used. However, in that case deprecation notice is logged into the console.

### 🎨 UI Changes

**Theme v1:**

[infinite_scroll_channel_list_theme_v1.webm](https://user-images.githubusercontent.com/32706194/194548030-09e2ef2f-b9cc-41b9-9262-4eeff609bfb4.webm)

**Theme v2:**

[infinite_scroll_channel_list_theme_v2.webm](https://user-images.githubusercontent.com/32706194/194548988-acf08d28-b8a1-400f-aa29-e6c1da9bb9a9.webm)

### CODE REVIEW

File: src/components/InfiniteScrollPaginator/InfiniteScroll.tsx [hunk 1]
```diff
@@ -10,43 +12,78 @@ const mousewheelListener = (event: Event) => {
...
   loader?: React.ReactNode;
-  loading?: React.ReactNode;
+  /**
+   * @desc Function that loads previous page with older items
+   * @deprecated Use loadPreviousPage prop instead. Will be removed with v11.0.0.
+   */
   loadMore?: () => void;
+  /**
+   * @desc Function that loads next page with newer items
+   * @deprecated Use loadNextPage prop instead. Will be removed with v11.0.0.
```
Comment (oliverlaz) [inline src/components/InfiniteScrollPaginator/InfiniteScroll.tsx:41]: I'm not sure whether we can plan the exact version where this property will get removed. I think we should start with creating a Github issue to remind us for cleaning this up and then we could plan/prioritize it accordingly.

File: src/components/InfiniteScrollPaginator/InfiniteScroll.tsx [hunk 2]
```diff
@@ -10,43 +12,78 @@ const mousewheelListener = (event: Event) => {
...
+  deprecationAndReplacementWarning(
+    [
+      [{ hasMoreNewer }, { hasNextPage }],
+      [{ loadMoreNewer }, { loadNextPage }],
+      [{ hasMore }, { hasPreviousPage }],
+      [{ loadMore }, { loadPreviousPage }],
+      [{ loader }, { LoadingIndicator }],
+    ],
+    'InfiniteScroll',
+  );
```
Comment (oliverlaz) [inline src/components/InfiniteScrollPaginator/InfiniteScroll.tsx:80]: Does this emit deprecation warnings on every render? If that is the case, I think we should log the deprecation message only once in order to prevent flooding the console with redundant log statements.

Comment (MartinCupela) [reply src/components/InfiniteScrollPaginator/InfiniteScroll.tsx]: @oliverlaz I have wrapped it with useEffect

File: src/components/InfiniteScrollPaginator/InfiniteScroll.tsx (hunk 1 above)
Comment (MartinCupela) [reply src/components/InfiniteScrollPaginator/InfiniteScroll.tsx:41]: @oliverlaz I have create the issue and its link to the comments. Thank you for reminding me this.

**Review by oliverlaz — DISMISSED** [review]

File: docusaurus/docs/React/custom-code-examples/channel-list-infinite-scroll.mdx [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+             Paginator={Paginator}
+             showChannelSearch
+/>
+```
+
+Especially the `threshold` prop may need to be set as the default is 250px. That may be too soon to load more channels.
+
+## What to take into consideration
+
+In order the infinite scroll can work, the element containing the `ChannelPreview` list has to be forced to display the scroll bar with the initial channel list load. This is achieved by:
```
Comment (petyosi) [inline docusaurus/docs/React/custom-code-examples/channel-list-infinite-scroll.mdx:51]:
```suggestion
For the infinite scroll to work, the element containing the `ChannelPreview` list has to be forced to display the scroll bar with the initial channel list load. This is achieved by:
```

**Review by oliverlaz — DISMISSED** [review]

File: docusaurus/docs/React/custom-code-examples/channel-list-infinite-scroll.mdx [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+## What to take into consideration
+
+For the infinite scroll to work, the element containing the `ChannelPreview` list has to be forced to display the scroll bar with the initial channel list load. This is achieved by:
+
+**1. adjusting the initial number of loaded channels**
+
+Set a reasonable number of channels to be initially loaded. If loading 10 channels leads to them being visible without having to scroll, then increase the number to e.g. 15:
+
+```tsx
+import { ChannelOptions, } from 'stream-chat';
```
Comment (arnautov-anton) [inline docusaurus/docs/React/custom-code-examples/channel-list-infinite-scroll.mdx:58]:
```suggestion
import { ChannelOptions } from 'stream-chat';
```

File: docusaurus/docs/React/custom-code-examples/channel-list-infinite-scroll.mdx [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+
+```tsx
+import {
+  ChannelList,
+  InfiniteScroll,
+  InfiniteScrollProps
+} from 'stream-chat-react';
+
+
+const Paginator = (props: InfiniteScrollProps) => <InfiniteScroll {...props} threshold={50}/>;
```
Comment (arnautov-anton) [inline docusaurus/docs/React/custom-code-examples/channel-list-infinite-scroll.mdx:38]:
```suggestion
const Paginator = (props: InfiniteScrollProps) => <InfiniteScroll {...props} threshold={50} />;
```

File: src/components/ChannelList/ChannelList.tsx [hunk 6]
```diff
@@ -350,8 +351,8 @@ const UnMemoizedChannelList = <
             ) : (
               <Paginator
                 hasNextPage={hasNextPage}
+                isLoading={channelsQueryState.queryInProgress === 'load-more'}
```
Comment (arnautov-anton) [inline src/components/ChannelList/ChannelList.tsx:354]: Would it make sense to "enumerize" stuff like `load-more`? Not sure how many other options are available.

Comment (MartinCupela) [reply src/components/ChannelList/ChannelList.tsx:354]: @arnautov-anton only two loading states are possible - initial load and `load-more` (pagination). I believe enumeration is not necessary.

**Review by arnautov-anton — APPROVED** [review]
